name = "dicobot-aggc"
main = "worker/index.js"
compatibility_date = "2024-08-30"

# システムプロンプトを環境変数として設定可能
# [vars]
# SYSTEM_PROMPT = "カスタムシステムプロンプトをここに設定"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "discobot-memos"
database_id = "d4de3d60-7767-499a-a8ad-f27fee9e67ed"

# Secrets should be added via wrangler secret
# wrangler secret put DISCORD_APPLICATION_ID
# wrangler secret put DISCORD_PUBLIC_KEY
# wrangler secret put DISCORD_BOT_TOKEN
# wrangler secret put GEMINI_API_KEY